server:
  port: 8761
spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${discountms.zipkin.url:http://localhost:9411/}
  application:
    name: eurekaserver
  profiles:
    active: ${eurekaserver.profiles.active:local}
  config:
    import: ${eurekaserver.config.url:configserver:http://localhost:8888}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
