--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: webauditms
    version: v1
  name: webauditms

spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: webauditms
      version: v1
  template: 
    metadata: 
      labels: 
        app: webauditms
        version: v1
    spec: 
      containers: 
        - 
          image: "kapilshekharraina/webauditasean01:latest"
          imagePullPolicy: Always
          name: webauditms
          ports: 
          - containerPort: 8077            
          env:
            - name:   webauditms.activeprofiles
              value: "dev"
            - name:   webauditms.configserver.labels
              value: "master"
            - name:   webauditms.configserverurl
              value: "http://configserver:8888"       
    #      resources:
    #        requests:
    #            memory: "256Mi"
    #            cpu: "500m"
    #        limits:
    #            memory: "786Mi"
    #            cpu: "1000m"  
