spring:
  cloud:
    stream:
      bindings:
        simpleDiscountPipeline-in-0:
          destination: ${discountstreamproc.binding.in.discpipe01.destination:TX-DISCOUNTSTREAM} #
          consumer:
           use-native-decoding: false
          group:  ${discountstreamproc.binding.in.discpipe01.group:simpleDiscountPipeline}  
        winaggdisc-in-0:
          destination:  ${discountstreamproc.binding.in.winaggdisc01.destination:TX-DISCOUNTSTREAM}
          consumer:
           use-native-decoding: false 
        winaggdisc-out-0:
          destination: ${discountstreamproc.binding.out.winaggdisc01.destination:TX-AGG-DISCOUNTSTREAM}
          #producer:
        windiscbyinstance-in-0:
          destination: ${discountstreamproc.binding.in.windiscbyinstance01.destination:TX-DISCOUNTSTREAM}
          consumer:
           use-native-decoding: false  
      function:
        definition: windiscbyinstance;winaggdisc      
      kafka:
        binder:
          brokers: kafka1:9094,kafka2:9095
        streams:
          binder:
            functions:
              winaggdisc:
               applicationId: winaggdisc-app
              windiscbyinstance:
               applicationId: windiscbyinstance-app
            configuration:
              commit.interval.ms: 1000
#              default:
#                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    bus:
      enabled: true
      destination: ${discountstreamproc.config.bus.exchange:busConfigExchange}

  application:
    name: discountstreamproc
  profiles:
    active: ${discountstreamproc.profiles.active:local}    
  config:
    import: ${discountstreamproc.config.url:configserver:http://localhost:8888}

  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${discountstreamproc.zipkin.url:http://192.168.99.103:9411/}

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${discountstreamproc.eureka.url:http://localhost:8761/eureka}

server:
  port: 9991

management:
  endpoints:
    web:
      exposure:
        include: "*"
#org.apache.kafka.streams.kstream.WindowedSerdes$TimeWindowedSerde
#Developers can leverage the framework’s content-type conversion for inbound and outbound conversion or switch to the native SerDe’s provided by Kafka.
                        